<!DOCTYPE html>
<html>
<head>
    <title>{{ $employee->name }} Details</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            background-color: #f5f6fa;
            margin: 0;
            padding: 30px;
            color: #333;
        }

        .container {
            max-width: 700px;
            margin: 0 auto;
            background-color: #ffffff;
            padding: 40px;
            border-radius: 15px;
            box-shadow: 0 8px 25px rgba(0,0,0,0.08);
        }

        .title {
            text-align: center;
            font-size: 30px;
            font-weight: 700;
            color: #1e293b;
            margin-bottom: 25px;
        }

        .profile-pic {
            display: block;
            margin: 0 auto 25px auto;
            width: 140px;
            height: 140px;
            border-radius: 50%;
            object-fit: cover;
            border: 4px solid #1e293b;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 16px;
            margin-top: 20px;
        }

        th, td {
            padding: 14px 16px;
            border-bottom: 1px solid #e2e8f0;
        }

        th {
            text-align: left;
            background-color: #1e293b;
            color: #ffffff;
            font-weight: 600;
            font-size: 17px;
        }

        tr:nth-child(even) {
            background-color: #f8fafc;
        }

        tr:hover {
            background-color: #e2e8f0;
        }

        .footer {
            text-align: center;
            margin-top: 30px;
            font-size: 13px;
            color: #6b7280;
            border-top: 1px solid #e2e8f0;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="container">
        <!-- Profile Picture -->
        @php
            if ($employee->profile_photo_path && file_exists(storage_path('app/public/' . $employee->profile_photo_path))) {
                $imagePath = storage_path('app/public/' . $employee->profile_photo_path);
                $type = pathinfo($imagePath, PATHINFO_EXTENSION);
                $data = file_get_contents($imagePath);
                $base64 = 'data:image/' . $type . ';base64,' . base64_encode($data);
            } else {
                $avatarUrl = "https://ui-avatars.com/api/?name=" . urlencode($employee->name) . "&background=ffffff&color=6c757d&size=200";
                $data = file_get_contents($avatarUrl);
                $base64 = 'data:image/png;base64,' . base64_encode($data);
            }
        @endphp
        <img src="{{ $base64 }}" class="profile-pic">

        <!-- Title -->
        <h1 class="title">{{ $employee->name }}</h1>

        <!-- Employee Info Table -->
        <table>
            <tr><th>Email</th><td>{{ $employee->email }}</td></tr>
            <tr><th>Role</th><td>{{ ucfirst($employee->role ?? 'N/A') }}</td></tr>
            <tr><th>Birthdate</th><td>{{ $employee->birthdate ?? 'N/A' }}</td></tr>
            <tr><th>Gender</th><td>{{ ucfirst($employee->gender ?? 'N/A') }}</td></tr>
            <tr><th>Joined At</th><td>{{ $employee->created_at->format('d M, Y') }}</td></tr>
            <tr><th>Last Updated</th><td>{{ $employee->updated_at->format('d M, Y') }}</td></tr>
        </table>

        <div class="footer">
            Generated by <strong>OptiStaff HR Management System</strong> | {{ now()->format('d M, Y H:i') }}
        </div>
    </div>
</body>
</html>
